yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_pages'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Слаг'
    )
    description = models.TextField(
        verbose_name='Описание группы'
    )

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группа'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Название группы',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:settings.COUNT_LETTERS_MODEL_POST]

    def clean(self):
        if self.text == 'yandex':
            raise ValidationError('Вы нашли пасхалку! :)')
        if self.text.isspace():
            raise ValidationError('Пробелы - зло')


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите комментарий'
    )

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'

    def __str__(self):
        return self.text

    def clean(self):
        if self.text == 'азазазаз!!!1!1!':
            raise ValidationError('Поздравляем, Вы тролль! :)')
        if self.text.isspace():
            raise ValidationError('Пробелы - зло')


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique_follow'
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='user_cannot_follow_himself'
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import create_paginator


@cache_page(20)
def index(request):
    posts = Post.objects.prefetch_related('author', 'group')
    page_obj = create_paginator(request, posts)
    return render(request, 'posts/index.html', {'page_obj': page_obj})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.prefetch_related('author')
    page_obj = create_paginator(request, posts)
    return render(request, 'posts/group_list.html', {'group': group,
                                                     'page_obj': page_obj})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    user_posts = user.posts.prefetch_related('group')
    page_obj = create_paginator(request, user_posts)
    post_follow = (
        request.user.is_authenticated
        and Post.objects.filter(
            author__following__user=request.user).exists()
    )
    return render(request, 'posts/profile.html', {'author': user,
                                                  'page_obj': page_obj,
                                                  'following': post_follow})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = Comment.objects.prefetch_related('post').filter(post=post_id)
    return render(
        request,
        'posts/post_detail.html',
        {
            'post': post,
            'form': form,
            'comments': comments
        })


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if request.method == 'POST' and form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST' and form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:post_detail', post.pk)
    return render(request, 'posts/create_post.html', {'form': form,
                                                      'is_edit': True,
                                                      'post': post})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_follow = Post.objects.filter(
        author__following__user=request.user
    )
    page_obj = create_paginator(request, post_follow)
    return render(request, 'posts/follow.html', {'page_obj': page_obj})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    is_following = Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    if request.user != author and not is_following:
        Follow.objects.create(user=request.user,
                              author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.filter(user=request.user,
                              author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <p>
    © {{ year }} Copyright <span style="color: red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/header.html
<header>
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-expand-lg navbar-light"
       style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        {% load static %}
        <img src="{% static 'img/logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block align-top"
             alt=""/>
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color: red">Ya</span>tube
      </a>
      <button class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse"
           id="navbarSupportedContent"
           style="flex-grow: inherit;">
        {% with request.resolver_match.view_name as view_name %}
          <ul class="nav nav-pills me-auto mb-2 mb-lg-0"
              style="justify-content: flex-end;">
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
                 href="{% url 'about:author' %}">Об авторе</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
                 href="{% url 'about:tech' %}">Технологии</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
                   href="{% url 'posts:post_create' %}">Новая запись</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name == 'auth:password_change' %}active{% endif %}"
                   href="{% url 'auth:password_change' %}">Изменить пароль</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name == 'auth:logout' %}active{% endif %}"
                   href="{% url 'auth:logout' %}">Выйти</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name == 'auth:logout' %}active{% endif %}"
                href="{% url 'posts:post_create' %}">Пользователь: {{ user.username }}</a>
                </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name == 'auth:login' %}active{% endif %}"
                   href="{% url 'auth:login' %}">Войти</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name == 'auth:signup' %}active{% endif %}"
                   href="{% url 'auth:signup' %}" >Регистрация</a>
              </li>
            {% endif %}
          </ul>
        {% endwith %}
      </div>
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post.html
{% load thumbnail %}
<article>
  <ul>
    {% if not is_profile %}
      <li>
        Автор: {% if post.author.get_full_name %} {{ post.author.get_full_name }}
        {% else %} {{ post.author.username }} {% endif %}
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
    {% endif %}
    <li>Дата публикации: {{ post.created|date:"d E Y" }}</li>
    {% if post.group %}
    <li>Группа: {{ post.group }}</li>
    {% endif %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
  </ul>
  <p>{{ post.text|linebreaks }}</p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if post.group %}
  </br>
  <a href="{% url 'posts:group_pages' post.group.slug %}">все записи группы</a>
{% endif %}
{% if request.user == post.author %}
</br>
<a href="{% url 'posts:post_edit' post.id %}">редактировать пост</a>
{% endif %}
</article>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}